### ISSUE TITLE
can i use these functions for 2-D data

### ISSUE THREAD

**Issue by mpsampat** [abelcarreras/cuda_functions#2]
Hi @abelcarreras ! 
Thanks for sharing! 
I was wondering if i can use these functions for 2-D images ? 

if so could you give me an example . 
thanks
Mehul

**Comment by abelcarreras** [comment]
Hi,

Unfortunately, at this moment 2D Fourier transform is not implemented.
CUDA FFT library (cuFFT) provides also functions to calculate 2D and 3D Fourier Transform:[https://docs.nvidia.com/cuda/cufft/index.html#function-cufftplan2d] so It shouldn't be very complicated to implement them using the same structure. However my CUDA card died recently and I can't continue the development for now until I get a new one (I hope soon).

Of course if you want to try to implement by yourself and contribute to this repository you're more than welcomed.
